# Generated by Django 3.0.3 on 2020-07-22 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20200721_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='name',
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
