# Generated by Django 3.0.3 on 2020-07-27 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20200727_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disike',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='disike',
            name='disliked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
