# Generated by Django 3.0.3 on 2020-07-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200727_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disike',
        ),
    ]
