# Generated by Django 3.0.3 on 2020-07-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_projectinductionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembers',
            name='requested_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
