# Generated by Django 3.0.3 on 2020-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0002_auto_20200721_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='url',
        ),
        migrations.AddField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
