# Generated by Django 3.0.3 on 2020-09-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0003_auto_20200921_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='order_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
